let project = [
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '약관동의',
    pageLink: '../charts-apexcharts.html',
    pageEnd: '22-05-24',
    pageModify: '22-05-25',
    worker: '김익중',
    state: '진행',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '약관동의',
    pageLink: '../charts-chartjs.html',
    pageEnd: '23-01-24',
    pageModify: '21-01-25',
    worker: '김익중',
    state: '진행',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '약관동의',
    pageLink: '../index.html',
    pageEnd: '23-02-14',
    pageModify: '23-05-25',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '약관동의',
    pageLink: 'ID1234567',
    pageEnd: '23-03-24',
    pageModify: '23-05-25',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '약관동의',
    pageLink: 'ID1234567',
    pageEnd: '19-05-24',
    pageModify: '23-05-25',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '약관동의',
    pageLink: 'ID1234567',
    pageEnd: '10-01-24',
    pageModify: '23-05-25',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '약관동의',
    pageLink: 'ID1234567',
    pageEnd: '23-05-24',
    pageModify: '23-05-25',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '약관동의',
    pageLink: 'ID1234567',
    pageEnd: '23-05-24',
    pageModify: '23-05-25',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '정보입력',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '검수',
    etc: '',
  },
  {
    depth2: '회원가입',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'popup',
    pageName: '약관보기',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '수정',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '수정',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '수정',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '수정',
    etc: '',
  },
  {
    depth2: '로그인',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '보류',
    etc: '',
  },
  {
    depth2: '가입완료',
    depth3: 'depth3',
    depth4: 'depth4',
    section: 'page',
    pageName: '가입완료',
    pageLink: 'ID1234564',
    pageEnd: '23-05-25',
    pageModify: '23-05-26',
    worker: '김익중',
    state: '완료',
    etc: '',
  },
  
]